version: '3.8'
services:
  book-service:
    build: ./book-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - book-network

  book-frontend:
    build: ./book-frontend
    ports:
      - "3000:3000"
    depends_on:
      - book-service
    networks:
      - book-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - book-service
      - book-frontend
    networks:
      - book-network

networks:
  book-network:
    driver: bridge
