version: '3.8'
services:
  book-service:
    build: ./book-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./book-service/src:/app/src
    networks:
      - book-network

  book-frontend:
    build:
      context: ./book-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./book-frontend/src:/app/src
    depends_on:
      - book-service
    networks:
      - book-network

networks:
  book-network:
    driver: bridge
